networks:
  dev:
    driver: bridge

services:
  db:
    image: postgres:15.8-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employeeUnitDB
    ports:
      - "5432:5432"
    networks:
      - dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
    depends_on:
        db:
          condition: service_healthy
    networks:
      - dev

volumes:
  postgres_data:
