name: Checks, Build, Publish, Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

#Builda e envia a img ao docker
  build:
    name: Build Image and Push to ACR (Azure container registry)
    needs: [checks]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push in Azure ACR
      run: |
        docker build . --file ./Dockerfile --tag ${{ secrets.DOCKER_IMAGE }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.DOCKER_IMAGE }}:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_IMAGE }}:latest
        docker push ${{ secrets.DOCKER_IMAGE }}:$GITHUB_RUN_NUMBER
        docker push ${{ secrets.DOCKER_IMAGE }}
  
  deploy:
    name: Deploying Az Web App
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      WEB_APP: employeeUnitManagementApi 

    steps:

      - name: Azure login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEB_APP }}
          images: ${{ secrets.DOCKER_IMAGE }}:latest
          slot-name: staging
